### ISSUE TITLE
개발자도구에서 소스코드가 보이지 않는 문제

### ISSUE THREAD

**Issue by deprecated-hongbiii** [mico-members/miracle-coding-blog#12]
Sources 탭에서 오리지널 소스코드가 안나오고 트랜스파일? 된 코드만 나와서 디버깅을 할 수가 없습니다.

**Comment by ppamppamman** [comment]
웹팩의 소스맵 부분을 작업하셔야 겠네요!

**Comment by deprecated-hongbiii** [comment]
`webpack.config.js` 에 `devtool: 'inline-source-map',` 라고 되어있긴 한데 안되네요 😭
사실 이슈만 써놓고 아직 안 찾아봤습니다. 하하 얼른 해결해야겠네요 감사합니다!!

**Comment by deprecated-hongbiii** [comment]
제가 착각했네요 잘 나옵니다!!
