### ISSUE TITLE
댓글 다는 pr 링크로 들어가는 버튼

### ISSUE THREAD

**Issue by wade3420** [mico-members/miracle-coding-blog#14]
문제점 : 홈페이지에서 링크로 바로 가면 댓글을 달기위해서 pr 페이지로 다시 찾아가야하는 번거로움이 있음
해결책 :  댓글달기 버튼을 누르면 pr 링크로 새탭이 열려서 댓글을 달수 있게 해줌
생각해볼 것 : tIl 링크로 가는 버튼이 어디까지여야할까? 

- 나중에 버전 1~2때는 저희 홈페이지 내에서 댓글을 달수있게 하는 것을 생각

**Comment by deprecated-hongbiii** [comment]
헉 저도 방금 이 이생각 했는데 !!!!!!
홈페이지 내에서 댓글 기능이 있으면 좋을지, PR 댓글이 좋을지는 아직 모르겠네요 🤤
유저의 의견을 들어보죠 🧐
