### ISSUE TITLE
modal ui style 변경 제안

### ISSUE THREAD

**Issue by wade3420** [mico-members/miracle-coding-blog#23]
성이 열심히 구현해주신것 알아서 조심스럽지만 

![screen-recording-_1_](https://user-images.githubusercontent.com/68339352/128220774-c9a3202f-9a2c-4a8a-8e81-d1b01fb9e373.gif)

체크박스가 생각보다 안이쁜거 같아서 이렇게 한번 바꿔보았습니다. 어떻습니까 ㅠㅠ

**Comment by deprecated-hongbiii** [comment]
와 예쁘네요!!! 🌼 체크박스도 괜찮긴 했움 ㅎㅎ

**Comment by GleamingStar** [comment]
디자인 너무예쁩니다!!!!
제가 구현한게 아니라 이먼 피그마가 구현한겁니다 ㅡㅡ 
전 디자인이 뭔지 몰라요 😒
