### ISSUE TITLE
필터링하고 pageNumber 추가한뒤에 또 필터링하면 2페이지 부터 보내는 버그 

### ISSUE THREAD

**Issue by wade3420** [mico-members/miracle-coding-blog#24]
필터링한 상태에서 페이지를 넘기고 다시 요청을 보내면 pageNum 이 2 인 채로 다시 보낸다. 
pageNum = 1 로 초기화 되는 로직이 필요하다. 필터링을 초기화하면 같이 초기화해주면 될듯

**Comment by GleamingStar** [comment]
`useEffect(()=>if(filterIndex.length===0) setPageNum(1), [filterIndex])`
