### ISSUE TITLE
의문의 필터링

### ISSUE THREAD

**Issue by juddroid** [mico-members/miracle-coding-blog#36]
![스크린샷 2021-08-06 22 19 27](https://user-images.githubusercontent.com/70361152/128516678-5e3d9497-81bc-4b24-b53c-7254d6fdaef2.png)

1. 특정멤버 undefined로 요청가는거 같아요!
2. 데이터가 없는 멤버 필터링이 안되는 것 같아요!

아기자기 귀여운 블로그네용!
미라클 모각코 응원합니다!

**Comment by deprecated-hongbiii** [comment]
버그 제보 감사합니다! 이어몬이 이슈를 닫은 걸 보니 해당 문제가 해결된 것 같습니다. 👍
