### ISSUE TITLE
모바일 브라우저에서 드롭다운 클릭 해제가 되지 않습니다.

### ISSUE THREAD

**Issue by teihong93** [mico-members/miracle-coding-blog#37]
### 재현환경
- iOS 14.6 safari

### 재현 경로
- 닉네임 드롭다운 클릭 -> 필터 설정 -> 필터를 한번 더 클릭했을 때 리스트의 결과는 제거되지만 드롭다운이 다시 그려지지 않습니다.

**Comment by teihong93** [comment]
모각코 화이팅입니닷~

**Comment by wade3420** [comment]
홀홀 감사합니다. 아마 모바일 환경에서는 클릭한뒤에 hover 와 focus가 유지되서 일어난 버그같네요! 수정하겠습니다
참고 링크 : https://pythonq.com/so/jquery/159071

**Comment by deprecated-hongbiii** [comment]
버그 제보 감사합니다! 문제를 해결했습니다.
